[project]
name = "nanochat"
version = "0.1.0"
description = "the minimal full-stack ChatGPT clone"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.0.0",
    "fastapi>=0.117.1",
    "kernels>=0.11.7",
    "psutil>=7.1.0",
    "rustbpe>=0.1.0",
    "tiktoken>=0.11.0",
    "tokenizers>=0.22.0",
    "torch==2.9.1",
    "uvicorn>=0.36.0",
    "wandb>=0.21.3",
    "zstandard>=0.25.0",
    "bitsandbytes>=0.48.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pytest>=8.0.0",
    "python-dotenv>=1.2.1",
    "transformers>=4.57.3",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# target torch to cuda 12.8 or CPU or gfx
[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "gpu" },
    { index = "pytorch-rocm-gfx120x", extra = "gfx120x" },
    { index = "pytorch-rocm-gfx1151", extra = "gfx1151" },
]

rocm = [
    { index = "pytorch-rocm-gfx120x", extra = "gfx120x" },
    { index = "pytorch-rocm-gfx1151", extra = "gfx1151" },
]

pytorch-triton-rocm = [
    { index = "pytorch-rocm-gfx120x", extra = "gfx120x" },
    { index = "pytorch-rocm-gfx1151", extra = "gfx1151" },
]

rocm-sdk-core = [
    { index = "pytorch-rocm-gfx120x", extra = "gfx120x" },
    { index = "pytorch-rocm-gfx1151", extra = "gfx1151" },
]

rocm-sdk-libraries-gfx120x-all = [
    { index = "pytorch-rocm-gfx120x", extra = "gfx120x" },
]

rocm-sdk-libraries-gfx1151 = [
    { index = "pytorch-rocm-gfx1151", extra = "gfx1151" },
]



[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm-gfx120x"
url = "https://repo.amd.com/rocm/whl/gfx120X-all"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm-gfx1151"
url = "https://repo.amd.com/rocm/whl/gfx1151"
explicit = true



[project.optional-dependencies]
cpu = [
    "torch==2.9.1",
]
gpu = [
    "torch==2.9.1",
]
gfx120x = [
    "torch>=2.9.1",
    "rocm",
    "pytorch-triton-rocm",
    "rocm-sdk-core",
    "rocm-sdk-libraries-gfx120x-all",
]
gfx1151 = [
    "torch>=2.9.1",
    "rocm",
    "pytorch-triton-rocm",
    "rocm-sdk-core",
    "rocm-sdk-libraries-gfx1151",
]

[tool.uv]
prerelease = "allow"
conflicts = [
    [
        { extra = "cpu" },
        { extra = "gpu" },
        { extra = "gfx120x" },
        { extra = "gfx1151" },
    ],
]
